[build]
builder = "nixpacks"
buildCommand = "dotnet restore && dotnet publish -c Release -o out"

[deploy]
startCommand = "dotnet out/BookApi.dll"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
